### ISSUE TITLE
V0.5 - Heart rate measurement does not start on re-boot.

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/PineTimeSD#13]
@seaside1 reported that enabling heart rate alarms when using pinetime resulted in continuous alarms.

This appears to be an issue with the PineTime not starting to measure heart rate automatically on boot.
The HRM LEDs illuminate, but the HR value displayed on the screen remains at zero - which is low enough to trigger an alarm.

I thought it started automatically, so need to look at what is happening.

**Comment by jones139** [comment]
I think I have found it.   By default the heart rate measurement shuts down when the watch display goes to sleep.  

You have to change the heart rate mode to continuous in the settings screen:
 
     - swipe right on main screen, 
     - press the cog icon, 
     - scroll up one page,
     - click on the 'heartrate' setting, 
     - change it to 'Cont' for continuous.   
     - It takes about 30 seconds to get the first heart rate value.
    
Continuous heart rate should be the default for OSD firmware - I do not think that updating the firmware changes the settings, so you only see this if you do a fresh install - an upgrade will keep your previous setting.

**Comment by jones139** [comment]
This should be fixed in v0.6 (https://github.com/OpenSeizureDetector/PineTimeSD/tree/v0.6)

And I have added a check to the installation instructions here:  https://openseizuredetector.github.io/pages-user/pine-time-installation.html

Thank you @seaside1 for pointing this out!

**Comment by seaside1** [comment]
Nice I'll test out the 0.6 shortly. As far as 0.5 goes, it works with the workaround.
