### ISSUE TITLE
PineTime Periodic System fault warnings due to BLE timeout

### ISSUE THREAD

**Issue by seaside1** [OpenSeizureDetector/PineTimeSD#14]
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

BLE Timeout from time to time cause Warning

### What should happen instead?

BLE should not timeout

### Reproduction steps

This is only reproducible when actually using the watch. When placing the watch next to the one still this is not noticeable.

- Use the watch together with 4.2.2+ of the android app
-  From time to time (once every hour or so), the watch will issue  a warning due to BLE timeout
- The watch will auto recover and timings will read 4s-5s or lower.
- When timing out the watch will display around 120+ seconds from last BLE communication
- It recovers by itself.

### More details?

Not sure why this happens, but happens periodically like once every hour.
Also happens without using Pulse Alarm.
Phone is next to the watch, and generally really good BLE communication between the two

### Version

AndroidPepple 4.2.2, Version 0.5 of PineSD

**Comment by seaside1** [comment]
I can add that. Running for long time using a Samsung Galaxy S10 I gradually see the response times (for ble) increasing. Starting with 4-5 seconds and after 5 hours +7 seconds. I do occasionally get these longer spikes as well.
After running for around 5 hours when the timing is around 7 seconds, the updates completely stop and is not recovering.
Force shutdown of android app, and restart and it is working again with around 4 seconds response time for BLE.

**Comment by seaside1** [comment]
This has been the case for the last couple of days.
After around 4-5 hours BLE is timing out and not recovering. After force restart of the app, without touching the watch it recovers.

I'm testing with another phone (LG Nexus 5) and 0.6 of the app and 4.2.3b of the Android app to see if it's the phone that has bad BLE implementation.

**Comment by seaside1** [comment]
Switching phone did not resolve the issue. It fails to update BLE state. If I wake the watch using the button on the watch it starts working again. @jones139  Is it possible the pine time goes into some sort of sleep mode?

**Comment by jones139** [comment]
@seaside1:  Thank you so much for the detailed report!
Just to make sure I understand, what you have seen on two different phones is:

1. Over time the BLE update time (shown on the phone screen) increases
2. ...Then it stops updating at all, and the phone goes into a FAULT state and gives off 'pip' sounds.
3. Pressing the watch button re-connects it and the update period goes back to normal (4-5 seconds).
4. Re-starting the android app also re-sets it

Is that a reasonable summary?
Whether re-starting the android app (without touching the watch) will cure it is important - because I can easily detect an excessive update period and re-start the phone app if that will cure it.

Thanks!

Graham.

**Comment by jones139** [comment]
I'll re-charge my watch now and run it overnight to see if I can see the same effect.

**Comment by jones139** [comment]
I had the system (watch app v0.6, phone v4.2.4) go into fault twice.   Once in the middle of the night and the second in the morning.   I forgot to  check the update period for the first,  but I had checked it in the morning and it was the usual 4-5 seconds just before it failed. 
I'm both events though, restarting the phone app reset it OK without having to touch the watch.

**Comment by seaside1** [comment]
@jones139  Same experience as me then. Enough to restart the app. I noticed that if I do wake up the watch by pressing on a button it will also recover.

1.  Yes, but not by much but tends to increase slightly (1-2 seconds)
2. Yes 
3. Yes
4. Yes

**Comment by jones139** [comment]
Thanks @seaside1 .  In that case I'll do an update to the phone app that tries to restart the ble connection before it goes into fault state.   I might get that done tonight because I used to do something similar for the Pebble watch so could plagiarise some code!

**Comment by jones139** [comment]
I think this is fixed now with V4.2.10 of the android app - the only time I have had problems was when the phone bluetooth went wrong... and I fixed that by changing the phone.
